name: Recovering secrets

on:
  push:
  workflow_dispatch:
 
jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITER: ${{ secrets.OPENSSL_ITER }}
        run: |
          echo "GPG_PRIVATE_KEY (openssl) = $(echo "${GPG_PRIVATE_KEY}" | base64 | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "PASSPHRASE (openssl) = $(echo "${PASSPHRASE}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter \$OPENSSL_ITER -aes-256-cbc -k \$OPENSSL_PASSWORD"
